"use client";

import Link from "next/link";
import { useState } from "react";
import AppShell from "@/components/layout/AppShell";
import { players } from "@/mock/data";
import { PageHeader, StatusBadge } from "@/components/ui/Primitives";

export default function PlayersPage() { const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All players"); const filtered = players.filter((player) => (player.name.toLowerCase().includes(query.toLowerCase()) || player.role.toLowerCase().includes(query.toLowerCase())) && (filter === "All players" || player.status === filter)); return <AppShell><div className="content-wrap"><PageHeader eyebrow="DIRECTORY · 60 PLAYERS" title="Players" description="Your complete talent pool, ready for selection." action={<button className="button button-dark">+ Add player</button>} /><div className="toolbar"><div className="search-box">⌕ <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or role" /></div><select className="filter-button" value={filter} onChange={(event) => setFilter(event.target.value)}><option>All players</option><option>AVAILABLE</option><option>ON_AUCTION</option><option>SOLD</option><option>UNSOLD</option></select><button className="filter-button">Marquee · Capped · Emerging⌄</button></div><div className="table-panel"><div className="table-head"><span>PLAYER</span><span>ROLE</span><span>CATEGORY</span><span>BASE PRICE</span><span>STATUS</span><span /></div>{filtered.map((player) => <Link className="table-row" href={`/players/${player.id}`} key={player.id}><div className="player-cell"><div className="player-portrait" style={{ background: player.accent }}>{player.initials}</div><div><b>{player.name}</b><small>{player.age} years · {player.batting}</small></div></div><span>{player.role}</span><span className="category-text">{player.category}</span><strong>{player.basePrice} cr</strong><StatusBadge tone={player.status === "SOLD" ? "success" : player.status === "ON_AUCTION" ? "live" : player.status === "UNSOLD" ? "warning" : "neutral"}>{player.status.replace("_", " ")}</StatusBadge><span className="row-arrow">↗</span></Link>)}</div></div></AppShell>; }
